spring.application.name=ipartubespring

spring.datasource.url=jdbc:sqlite:ipartube.db
spring.datasource.username=
spring.datasource.password=password

spring.jpa.show-sql=true
# spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.open-in-view=false

spring.data.rest.base-path=/api/v1

springdoc.swagger-ui.path=/openapi
# springdoc.swagger-ui.path=/swagger-ui.html

springdoc.api-docs.path=/openapi/api-docs
# springdoc.api-docs.path=/v3/api-docs

# springdoc.swagger-ui.enabled=true
# springdoc.api-docs.enabled=true
