spring.application.name=restaurantespring

# JDBC
spring.datasource.url=jdbc:sqlite:restaurante.db
spring.datasource.username=
spring.datasource.password=

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
