spring.application.name=restaurantespring

# JDBC
spring.datasource.url=jdbc:sqlite:restaurante.db
spring.datasource.username=
spring.datasource.password=

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# JSP
# spring.mvc.view.prefix=/WEB-INF/vistas/
# spring.mvc.view.suffix=.jsp

# DevTools
spring.devtools.livereload.enabled=true

# Rest Repositories
spring.data.rest.base-path=/api/v1
